export const environment = {
  production: true,
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc19hZG1pbiI6dHJ1ZSwidXNlcl9pZCI6MSwidXNlcl9uYW1lIjoibWFrbWFpZC5tdWxhYmVnb3ZpY0BzdHUuc3NzdC5lZHUuYmEiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiLCJ0cnVzdCJdLCJleHAiOjE2MjM4NTUyMzIsImp0aSI6IjY4NmJmYmI4LWM1YzctNDJjOS1hNTg2LWUyMzUxMWQwOTIxMCIsImNsaWVudF9pZCI6Im1kbWEtY2xpZW50In0.N7ZkXeJcvK4bL0LSbDOE2WwiijMNrSjy3yxqpDmVHic",
  apiBaseUrl: 'https://mdma-back.herokuapp.com/api/' // ovdje link od heroku-a
};
